language: ruby

sudo: true

dist: trusty

before_install:
- docker pull carlad/sinatra
- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start"


script:
- curl localhost:80; echo
- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
