sudo: required

services:
  - docker

before_install:
- docker pull wmuengineer/sinatra
- docker run -d -p 127.0.0.1:80:4567 wmuengineer/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker run wmuengineer/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- bundle exec rake test
